title: TB025
description: >-
  Sitio web del curso TB021 Paradigmas de Programación - Corsi / Essaya - FIUBA.
domain: algoritmos3ce.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://algoritmos3ce.github.io"
theme: minima
defaults:
  - scope:
      path: ""
    values:
      layout: page
header_pages:
  - calendario.md
  - entorno/index.md
  - material.md
  - tps.md
  - links.md
liquid:
  error_mode: strict
strict_front_matter: true
