title: TB025
description: >-
  Sitio web del curso TB025 Paradigmas de Programación - Corsi / Essaya - FIUBA.
domain: algoritmos3ce.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://algoritmos3ce.github.io"
theme: just-the-docs
liquid:
  error_mode: strict
strict_front_matter: true

aux_links:
  Editar en Github: https://github.com/algoritmos3ce/algoritmos3ce.github.io

search: true
enable_copy_code_button: true

favicon_ico: "/assets/favicon.ico"

callouts:
  nota:
    title: Nota
    color: blue
  importante:
    title: Importante
    color: yellow
  advertencia:
    title: Advertencia
    color: yellow
  cuidado:
    title: Cuidado
    color: red
